/**********************************************
* Author       : Rambabu Sapa PCCTG 
* Date         :04/16/2015
* Description  :// UCC Data Sales Procedures 
**********************************************/

namespace Helper
{
    public static class DBCommands
    {
        public const string USP_UCC_DATASALES_SCHEDULER_UCCLIEN = "[BSS].USP_UCC_DATASALES_SCHEDULER_UCCLIEN";// UCC Lien Details 
        public const string USP_UCC_DATASALES_SCHEDULER_UCCCOLLATERALTEXT = "[BSS].USP_UCC_DATASALES_SCHEDULER_UCCCOLLATERALTEXT";//UCC Collateral
        public const string USP_UCC_DATASALES_SCHEDULER_CNSPRODUCTS = "[BSS].USP_UCC_DATASALES_SCHEDULER_CNSPRODUCTS"; //CNS Collateral

        #region Data Sales Latest

        public const string USP_UCC_DATASALES_SCHEDULER_UCCFILING = "[BSS].USP_UCC_DATASALES_SCHEDULER_UCCFILING";// UCC Filing Details 
        public const string USP_UCC_DATASALES_SCHEDULER_DEBTORS = "[BSS].USP_UCC_DATASALES_SCHEDULER_DEBTORS";// UCC Debtor 
        public const string USP_UCC_DATASALES_SCHEDULER_UCCFILING_AMEDNMENTS = "[BSS].[USP_UCC_DATASALES_SCHEDULER_UCCFILING_AMEDNMENTS]";  
        public const string USP_UCC_DATASALES_SCHEDULER_SECUREDPARTIES = "[BSS].USP_UCC_DATASALES_SCHEDULER_SECUREDPARTIES";// UCC Secured Party    
        public const string USP_UCC_DATASALES_SCHEDULER_FILINGIMAGEPATHS = "[BSS].[USP_UCC_DATASALES_SCHEDULER_FILINGIMAGEPATHS]";// Image Paths

        #endregion

        //public const string USP_GET_UCCDATASALES = "BFS.usp_get_uccdatasales";
        //public const string USP_GET_UCCDATASALESDOCUMENTS = "BFS.usp_get_uccdatasalesdocuments";
        //public const string USP_INSERTUCCDATASALESSCHEDULER = "BFS.usp_insertuccdatasalesscheduler";
        // Data Sales 
        //public const string USP_UCC_DATASALES_REQUESTDETAILS = "[BSS].USP_UCC_DATASALES_REQUESTDETAILS";
        //public const string USP_UCC_DATASALES_REQUESTS = "[BSS].USP_UCC_DATASALES_REQUESTS";
        //public const string USP_UCC_DATASALES_SCHEDULER = "[BSS].USP_UCC_DATASALES_SCHEDULER";
        public const string USP_UCC_DATASALES_SCHEDULER_ASL1COLLATERAL = "[BSS].USP_UCC_DATASALES_SCHEDULER_ASL1COLLATERAL";
        public const string USP_UCC_DATASALES_SCHEDULER_ASL2COLLATERAL = "[BSS].USP_UCC_DATASALES_SCHEDULER_ASL2COLLATERAL";
        public const string USP_UCC_DATASALES_SCHEDULER_ASL3COLLATERAL = "[BSS].USP_UCC_DATASALES_SCHEDULER_ASL3COLLATERAL";
        public const string USP_UCC_DATASALES_SCHEDULER_ASL5COLLATERAL = "[BSS].USP_UCC_DATASALES_SCHEDULER_ASL5COLLATERAL";


        public const string USP_UCC_DATASALES_SCHEDULER_FEDERALJUDGMENTINFO = "[BSS].USP_UCC_DATASALES_SCHEDULER_FEDERALJUDGMENTINFO";
        public const string USP_UCC_DATASALES_SCHEDULER_FEDERALTAXSERIALNOINFO = "[BSS].USP_UCC_DATASALES_SCHEDULER_FEDERALTAXSERIALNOINFO";
        public const string USP_UCC_DATASALES_SCHEDULER_MSL = "[BSS].USP_UCC_DATASALES_SCHEDULER_MSL";
        public const string USP_UCC_DATASALES_SCHEDULER_UCCCORRECTION = "BSS.USP_UCC_DATASALES_SCHEDULER_UCCCORRECTION";
        public const string USP_UCC_DATASALES_SCHEDULER_STATETAXFILINGINFO = "BSS.USP_UCC_DATASALES_SCHEDULER_STATETAXFILINGINFO";

        public const string USP_UCC_DATASALES_SCHEDULER = "[BSS].[USP_UCC_DATASALES_SCHEDULER]";
        public const string USP_UCC_REPORTSALES_SCHEDULER = "[BSS].[USP_UCC_REPORTSALES_SCHEDULER]";
    }
}
